import SIDELvConservation.ZeroActingPairing
open SIDELvConservation.RegisterPentagon
#print axioms zeroActingPairing_to_channelInequality
#print axioms zeroActingPairing_to_RH
#print axioms distinctFromInput_discharged
